-- Collection Methods
    -- COUNT        - Return's the number of elements in a collection
    -- EXITS(n)     - Return's True of False to indicate whether the specified element exits
    -- FIRST        - Return's the index of the First element in the collection
    -- LAST         - Return's the index of the Last element in the collection
    -- PRIOR(n)     - Return's the index of the element Prior to the specific element
    -- NEXT(n)      - Return's the index of the element Next to the specific element
    -- LIMIT        - Return's the maximum number of element allowed in a VARRAY
    -- EXTEND       - Increase a single NULL element to the collection (Nested table or VARRAY)
    -- EXTEND(n)    - Increase a(n) NULL element to the collection (Nested table or VARRAY)
    -- TRIM         - Removes single element from the end of the collection
    -- TRIM(n)      - Removes (n) elements from the end of the collection
    -- DELETE       - Delete all element from the collection
    -- DELETE(n)    - Delete(n) elements from the collection